version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: db
    hostname: pg
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8080:8080"
    volumes:
      - ./api/swagger.json:/app/swagger.json

volumes:
  database-data:
